name: CI
on:
  pull_request:
  workflow_dispatch:

env:
  DENO_DIR: ./cache

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.33.x

      - name: Cache Deno dependencies 
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}
      
      - name: Format
        run: deno fmt src --check
        
      - name: Lint
        run: deno lint src

      - name: Test
        run: |
          deno test src \
            --allow-read=fixtures \
            --allow-net=unpkg.com,raw.githubusercontent.com \
            --allow-env=CI
